# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xii79PR2758-NSjugumIiSxKSsmJlxXf
"""

import xarray as xr
import numpy as np
import pandas as pd
import glob

from google.colab import drive
drive.mount('/content/drive')

# MTmax

PISCOt2_MTmax = []
for i in np.arange(1981, 2021):
  name_file = "tmax_daily_YI.nc".replace("YI", str(i))
  url_name_file = "/content/drive/MyDrive/DATA_research/PISCOt/version_release_candidate_rc/tmax/" + name_file
  file_data = xr.open_dataset(url_name_file)
  file_data = file_data.sel(latitude=-6.75028, longitude=-79.6002799999999, method = "nearest" ).to_dataframe().reset_index()
  PISCOt2_MTmax.append(file_data)

PISCOt2_MTmax = pd.concat(PISCOt2_MTmax, axis=0)
PISCOt2_MTmax.set_index('time', inplace = True)

PISCOt2_MTmax.drop(["longitude", "latitude"], axis = 1).to_csv("/content/drive/MyDrive/PISCOt_big_data/global_gridded_products/PISCOt_v1.2/PE106106_tmax.csv")

# MTmin

PISCOt2_MTmin = []
for i in np.arange(1981, 2021):
  name_file = "tmin_daily_YI.nc".replace("YI", str(i))
  url_name_file = "/content/drive/MyDrive/DATA_research/PISCOt/version_release_candidate_rc/tmin/" + name_file
  file_data = xr.open_dataset(url_name_file)
  file_data = file_data.sel(latitude=-6.75028, longitude=-79.6002799999999, method = "nearest" ).to_dataframe().reset_index()
  PISCOt2_MTmin.append(file_data)

PISCOt2_MTmin = pd.concat(PISCOt2_MTmin, axis=0)
PISCOt2_MTmin.set_index('time', inplace = True)

PISCOt2_MTmin.drop(["longitude", "latitude"], axis = 1).to_csv("/content/drive/MyDrive/PISCOt_big_data/global_gridded_products/PISCOt_v1.2/PE106106_tmin.csv")

# MTmax

PISCOt2_MTmax = []
for i in np.arange(1981, 2021):
  name_file = "tmax_daily_YI.nc".replace("YI", str(i))
  url_name_file = "/content/drive/MyDrive/DATA_research/PISCOt/version_release_candidate_rc/tmax/" + name_file
  file_data = xr.open_dataset(url_name_file)
  file_data = file_data.sel(latitude=-13.3631305555556, longitude=-71.6733611111111, method = "nearest" ).to_dataframe().reset_index()
  PISCOt2_MTmax.append(file_data)

PISCOt2_MTmax = pd.concat(PISCOt2_MTmax, axis=0)
PISCOt2_MTmax.set_index('time', inplace = True)

PISCOt2_MTmax.drop(["longitude", "latitude"], axis = 1).to_csv("/content/drive/MyDrive/PISCOt_big_data/global_gridded_products/PISCOt_v1.2/PE113116_tmax.csv")

# MTmin

PISCOt2_MTmin = []
for i in np.arange(1981, 2021):
  name_file = "tmin_daily_YI.nc".replace("YI", str(i))
  url_name_file = "/content/drive/MyDrive/DATA_research/PISCOt/version_release_candidate_rc/tmin/" + name_file
  file_data = xr.open_dataset(url_name_file)
  file_data = file_data.sel(latitude=-13.3631305555556, longitude=-71.6733611111111, method = "nearest" ).to_dataframe().reset_index()
  PISCOt2_MTmin.append(file_data)

PISCOt2_MTmin = pd.concat(PISCOt2_MTmin, axis=0)
PISCOt2_MTmin.set_index('time', inplace = True)

PISCOt2_MTmin.drop(["longitude", "latitude"], axis = 1).to_csv("/content/drive/MyDrive/PISCOt_big_data/global_gridded_products/PISCOt_v1.2/PE113116_tmin.csv")

